-- =============================================================================
-- MULTI-AGENT TECHNICAL SERVICE, SALES AND SUPPORT SYSTEM
-- POSTGRESQL DATABASE CREATION SCRIPT

-- =============================================================================
-- 1. ENUM TYPE DEFINITION
-- =============================================================================

CREATE TYPE user_role_enum AS ENUM ('CUSTOMER', 'TECHNICIAN', 'ADMIN');
CREATE TYPE request_type_enum AS ENUM ('REPAIR', 'SALE', 'SUPPORT');
CREATE TYPE ticket_status_enum AS ENUM (
    'NEW',
    'IN_DIAGNOSIS',
    'QUOTED',
    'IN_REPAIR',
    'READY_FOR_PICKUP',
    'DELIVERED',
    'CANCELLED'
);
CREATE TYPE quote_status_enum AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');
CREATE TYPE notification_type_enum AS ENUM ('QUOTE_CONFIRMATION', 'PICKUP_NOTICE', 'STATUS_CHANGE');

-- =============================================================================
-- 2. SYSTEM TABLE CREATION
-- =============================================================================
-- -----------------------------------------------------------------------------
-- TABLE: users
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    role user_role_enum NOT NULL DEFAULT 'CUSTOMER',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

-- -----------------------------------------------------------------------------
-- TABLE: recovery_tokens
-- -----------------------------------------------------------------------------
CREATE TABLE recovery_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- TABLE: spare_parts (Inventory)
-- -----------------------------------------------------------------------------
CREATE TABLE spare_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    unit_price NUMERIC(10, 2) NOT NULL,
    current_stock INT NOT NULL DEFAULT 0,
    minimum_threshold INT NOT NULL DEFAULT 5,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_positive_unit_price CHECK (unit_price >= 0),
    CONSTRAINT chk_positive_stock CHECK (current_stock >= 0),
    CONSTRAINT chk_positive_threshold CHECK (minimum_threshold >= 0)
);

-- -----------------------------------------------------------------------------
-- TABLE: tickets
-- -----------------------------------------------------------------------------
CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    technician_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(200) NOT NULL,
    failure_description TEXT NOT NULL,
    request_type request_type_enum NOT NULL DEFAULT 'REPAIR',
    status ticket_status_enum NOT NULL DEFAULT 'NEW',
    provisional_diagnosis TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- TABLE: quotes
-- -----------------------------------------------------------------------------
CREATE TABLE quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL UNIQUE REFERENCES tickets(id) ON DELETE CASCADE,
    labor_cost NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    parts_cost NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    status quote_status_enum NOT NULL DEFAULT 'PENDING',
    observations TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_positive_labor_cost CHECK (labor_cost >= 0),
    CONSTRAINT chk_positive_parts_cost CHECK (parts_cost >= 0),
    CONSTRAINT chk_positive_total_amount CHECK (total_amount >= 0)
);

-- -----------------------------------------------------------------------------
-- TABLE: quote_details
-- -----------------------------------------------------------------------------
CREATE TABLE quote_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id BIGINT NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
    spare_part_id BIGINT NOT NULL REFERENCES spare_parts(id) ON DELETE RESTRICT,
    quantity INT NOT NULL DEFAULT 1,
    unit_price NUMERIC(10, 2) NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    CONSTRAINT chk_positive_quantity CHECK (quantity > 0),
    CONSTRAINT chk_positive_subtotal CHECK (subtotal >= 0)
);

-- -----------------------------------------------------------------------------
-- TABLE: notification_history
-- -----------------------------------------------------------------------------
CREATE TABLE notification_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES tickets(id) ON DELETE SET NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_type notification_type_enum NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    sent_successfully BOOLEAN NOT NULL DEFAULT FALSE,
    error_message TEXT,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 3. QUERY OPTIMIZATION INDEXES
-- =============================================================================

CREATE INDEX idx_tickets_customer_id ON tickets(customer_id);
CREATE INDEX idx_quote_details_quote_id ON quote_details(quote_id);

-- =============================================================================
-- 4. AUTOMATIC TRIGGER FOR UPDATED_AT
-- =============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_spare_parts_updated_at BEFORE UPDATE ON spare_parts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_tickets_updated_at BEFORE UPDATE ON tickets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_quotes_updated_at BEFORE UPDATE ON quotes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

